### ISSUE TITLE
[API Engine] To develop end to end the command 3;

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#10]
To develop the command 3 already integrated in the API engine:

Receive: 3;0; or 3;100; or 3;X; X between (1..99)
Call the southbound: 
0 or 100 -> OFF / ON Relay. Call #2 
1..99 -> ON Relay && 0-10V. Call #11

**Comment by juanra-bascones** [comment]
I have (what I trust is) all the elements taking part in this command: the Context Variable (integer, no limited..), the simple metadata for the command, etc...
I have tested quite intenselly (with sockets..) and it seems to have a correct bahaviour .
In order to make easier the (pending, so far) propagation to the southbound, I have dummy placeholders for the real wrappers.
I hope we can test it soon in external over the real thing

**Comment by juanra-bascones** [comment]
The command is implemented in external, and has been tested (in an quite isolated way, as described in issue #13) within a Integration_tests branch.
It lacks the real connection with the actuators, for which there are some placeholders already written.

**Comment by ralcaide** [comment]
Waiting to #11 in order to finish the development and testing of this command

**Comment by ralcaide** [comment]
Modification of the description:

3;0;..3;10; -> RelayDeactivation
3;11;..3;100; -> RelayActivation + Dimming(X)

**Comment by sinapseenergia** [comment]
A n additional consideration here:

Normally we use dimming function in order to make "soft" starts and stops

The secuence described have to be exactly:

**3:0;..3;10;--> Dimming(first) --> Delay(ms) --> Relay Off
3;X (X>10); Relay ON --> Dimming to X value**  

the objetive here is mainly:
Switch off with the minimum electrical Load
Swicth on with the minimum electrical demand

**Comment by juanra-bascones** [comment]
I have just coded this conditions in the "Write_DSTAT" function, which acts as front-end  for executing the changes in the DSTAT (dimming current value) variable.
I have been testing it under the debugger and it looks to beahave as expected.
(nevertheless I dont see any change in the lamp connected to 'external').
I can't arrange to execute it out of the debugger, in order to see it to change

**Comment by ralcaide** [comment]
Comments added to the commit. Please check them:

https://github.com/Sinapse-Energia/EC-M2M/commit/f88d27fb3915c0b4811972e88d5fe85b94c4d8bf

**Comment by ralcaide** [comment]
I've tested and everything seems ok but the 3;0; doesn't turn off the lamp. I think, the relay of the device in Sinapse is not connected. Tomorrow should be connected and tested.

**Comment by ralcaide** [comment]
Tested and working good in alfa version
