### ISSUE TITLE
[API Engine] To develop end to end the command 1;

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#13]
In order to get the status of the device it is necessary to understand and answer the command 1; of the VF and Sinapse API

**Comment by juanra-bascones** [comment]
What do we do, for this milestone with the variables?
How do we do for reading the sensors, and moving the value into the context?
Or are we going to put static values in all of them (except for the dimming, of course)?

**Comment by ralcaide** [comment]
We will display the real values only of the following vars:

STAT = 0 / 1 (Southbound relay)
DSTAT = 0..100 (Southbound 0-10V)

The other values will be static values by the moment

**Comment by juanra-bascones** [comment]
Ok.
The constructor of the class CVariable, allows an optional parameter, that is used as initial value. 
By now, we can put reasonable values there , so we can "forget" most of the variables.
For STAT we have to build  a couple of functions (for set and get..).
For DSTAT, we need the 'set' for sure, but maybe we can avoid building the get and taking the value from the Context....       
Let me know "reasonable" values for all the rest of the stuff, and I will use them as the initial value for each one.

**Comment by juanra-bascones** [comment]
I have all the stuff taking part in the complete cycle of this command, specially, for the meassurement message it has to reply. 
I have already defined ALL the variables that are part of the message (many..) each one with the type (string, integer, decimal...) I have thought correct.
I have also, the conection between the context variables and placeholders for de southbound reading wrappers (Voltage, Temperature, etc...). 
I have tested quite intenselly (over sockets with VStudio,..) sending and receiving from a MQTT.fx console, and it looks pretty well.
I think is ready for testing over M95 in external

**Comment by juanra-bascones** [comment]
The only "hangling" item is the node ID.
In this versión there is a main-level string variable, hadcoded to same arbitrary value.
The important point es that this same value is used in the only suscribing item (LU/LUM/ACT/xxx) and also in the ID position of the meassurement message.
Thus, only will be necesary to adjust the initial value of de Id string, in order to have both things consistent each other

**Comment by juanra-bascones** [comment]
In a quite flexible meaning, the command 1; is already implemented and succesfully tested.
By now, the tests have been done without any integration with the middleware nor the devices and sensors.
The tests has been driven using literal strings in place of real messages, and getting the expected measurement message. 
A little code snippet (in the main program, just after basic initialization) has been included for driving those tests. 
Although the test has been, because of that, little realistic, the results allow to deduct that the engine for proccessing the messages works as expected.
Further regression tests have to be run when the middleware and the southbound wrappers were fully performant.

**Comment by ralcaide** [comment]
Command tested without #11. Waiting this issue to close this one

**Comment by ralcaide** [comment]
tested - Branch alfa version
