### ISSUE TITLE
[DEBUG] To avoid publication of debug traces in release mode

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#24]
The devices to be send to Vodafone should not publish traces. This will consume a lot of data

**Comment by juanra-bascones** [comment]
It makes full of sense.
However, I propose to keep a minimum level of information (let's call it an activity log) even in release mode. At least a message on broker connection or reconnection, telling the topic subscription.

**Comment by juanra-bascones** [comment]
In order to achieve the best and simplest implementation of this issue, we would like to have some reliable hint from the compiler (a macro set by the compiler/IDE, telling which configuration is being build).

I haven´t found nothing like this, but maybe we can explicitally include a compiler switch ( -D DEBUG ) only in the trace compiler options
In the meanwhile let's have the same preprocersor symbol set manually ina very common place (definitions.h), so the source can be written in a neutral and ultimate form.

**Comment by juanra-bascones** [comment]
There is a commit in origin with this enhacement.
It uses the presence/absence of a macro (DEFINE) in the file definitions.h
If DEBUG is NOT defined, the only trace message is on connection to broker

**Comment by ralcaide** [comment]
Great, @juanra-bascones could we close this issue?. The searching or development of a macro to ease the debug/release features should be done in another issue TO BE CREATED

**Comment by juanra-bascones** [comment]
OK.
Let's close it.
