### ISSUE TITLE
[MAIN Program] Development of the Main program following the flow diagram explained in the README

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-M2M#9]
To develop the main program of the EC-M2M FW. Basically it should be developed the flow diagram explained in the README:

- Init the system & load non-volatile vars
- Manage the GPRS & MQTT connectivity, each time that the timeouts are over:

1. Check MQTT Connection & GPRS Connection
2. If MQTT OFF && GPRS ON -> Connect MQTT, then manage subscriptions
3. If MQTT OFF && GPRS OFF -> Connect GPRS, then Connect MQTT, then manage subscriptions

- Receive MQTT commands 
- Invoke the API engine for each MQTT received
- API engine should manage each command and act in consequence (southbound && publishing messages)

**Comment by juanra-bascones** [comment]
As far as some input messages  (at least one, in the VF case)  require inmediate reply, I think maybe is better to relate this in the main loop.
I am now working with a first version of this main loop section.
The point is to provide proper return value for  the message-processing-method of the engine  (the reply message or NULL...),  so that, I could be sended inmediately from the main loop after method return .

**Comment by juanra-bascones** [comment]
Building the main loop segment handling the messages, I am facing some trouble about where and how handle the information. More preciselly, the topic each message belongs to.
The problem involves several aspects (the C nature of the main program, the dynamic nature of some topics,....), making me quite difficult to figure out the better solution rigth now.
In order to decouple this issue and de prototype milestone for VF, the question is:
Is it requiered for this beta version to send out any messages?
If so, should it be feasible to have just one fixed publish topic where all those messages could be sended out?

**Comment by ralcaide** [comment]
I answer your questions:
- Yes, it will be needed to publish something: We will receive also commands 1;
- For VF, we need the following topics
Regular data: SC/ES/RI/LI/SI/SEN (QoS0)
Alerts: SC/ES/RI/LI/SI/ALE (QoS0) -> NOT NECESSARY FOR MILESTONE 2
Subscription: SC/ES/RI/LI/SI/ACT/DEVICE_ID -> Where our devices should be subscribed

**Comment by ralcaide** [comment]
To improve the connection / reconnection loop

**Comment by juanra-bascones** [comment]
I have been making some tests with the (quite incomplete) current implementation of the loop, and it  behaves fine as far as the commands arrive in a regular basis....
Conversely, when the message flow is scarce, sooner or later you end having a HardFault, because of the attempt to read for messages in a closed connection (either by the mqtt broker or by the TCP protocol)
I have "overused" the trace facility (sending traces on each while iteration, even if there isné messages to read), and the system seems to run in a very stable way (with the cost of having one useless trace message every 10 seconds).
I know taht it`s planned to have a kind of MQTT-Ping in order to keep activity in the conection, without having to overload the trace nor the log.
Nevertheless I think, we need (in addition to this ping or heart-beat), an aditional function in the transport level (and the corresponding one in the mqtt wrapper) to test if the connection is still alive, because rigth now the connection handle is just a local variable that doesn´t reflect any possible change in the real conection status.
We'll have to make some arrangement in order to implement these status() or check()  function in both communication wrappers, but just for now, I'm going to define a provisional dummy placeholder for using it in a second version of the loop as soon as possible.

**Comment by ralcaide** [comment]
Tested and working. Now the maximum stable frequency is one message each 2 seconds
